name: Deploy

on:
  push:
    tags:
      - 'v*'  # Ð¢ÐµÐ³Ð¸ Ð²Ð¸Ð´Ð° v0.1.0

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
      HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      REDIS_URL: ${{ secrets.REDIS_URL }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}



    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: SSH and deploy with docker-compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
          
            mkdir -p ~/apps
            cd ~/apps
          
            if [ -d "site-snoop-bot/.git" ]; then
              echo "ðŸŒ€ Pulling latest changes in site-snoop-bot"
              cd site-snoop-bot
              git pull
            else
              echo "ðŸ“¥ Cloning fresh copy of site-snoop-bot"
              git clone git@github.com:eugene-ruby/site-snoop-bot.git
              cd site-snoop-bot
            fi
            echo "${{ env.HARBOR_PASSWORD }}" | docker login harbor.in.vocabapp.ru -u ${{ env.HARBOR_USERNAME }} --password-stdin
            
            echo "â¬‡ï¸  Pulling Base Docker image"
            docker pull harbor.in.vocabapp.ru/projects/ruby-ruby3.4-node-chrome:latest
            echo "â¬‡ï¸  Build App Docker image"
            docker build -t harbor.in.vocabapp.ru/projects/site-snoop-app:latest .
            docker push harbor.in.vocabapp.ru/projects/site-snoop-app:latest

            echo "ðŸ’¾ Writing .env"
            echo "TELEGRAM_BOT_TOKEN=${{ env.TELEGRAM_BOT_TOKEN }}" > .env
            echo "REDIS_URL=${{ env.REDIS_URL }}" >> .env
            echo "DATABASE_URL=${{ env.DATABASE_URL }}" >> .env

            echo "ðŸ”„ Restarting with docker-compose"
            docker-compose down
            docker-compose pull
            docker-compose up -d

